<?xml version="1.0" encoding="utf-8"?><Database Name="FishingShopDB" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6FKP8QV\SQLEXPRESS;Initial Catalog=FishingShopDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FishingShopDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Category">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Items" Member="Items" ThisKey="Id" OtherKey="IdCategory" Type="Items" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Items">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="IdCategory" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Desctription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lenght" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CodeBaits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Category_Items" Member="Category" ThisKey="IdCategory" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdminRole" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>